JEIEvents.hideItems(event => {

  // ProjectE

  event.hide('projecte:dm_pick')
  event.hide('projecte:dm_axe')
  event.hide('projecte:dm_shovel')
  event.hide('projecte:dm_hoe')
  event.hide('projecte:dm_shears')
  event.hide('projecte:dm_hammer')
  event.hide('projecte:rm_pick')
  event.hide('projecte:rm_axe')
  event.hide('projecte:rm_shovel')
  event.hide('projecte:rm_hoe')
  event.hide('projecte:rm_shears')
  event.hide('projecte:rm_hammer')
  event.hide('projecte:rm_morning_star')
  event.hide('projecte:destruction_catalyst')
  event.hide('projecte:low_covalence_dust')
  event.hide('projecte:medium_covalence_dust')
  event.hide('projecte:high_covalence_dust')
  event.hide('projecte:alchemical_chest')
  event.hide('projecte:condenser_mk1')
  event.hide('projecte:condenser_mk2')
  event.hide('projecte:collector_mk1')
  event.hide('projecte:collector_mk2')
  event.hide('projecte:collector_mk3')
  event.hide('projecte:relay_mk1')
  event.hide('projecte:relay_mk2')
  event.hide('projecte:relay_mk3')
  event.hide('projecte:dm_pedestal')
  event.hide('projecte:white_alchemical_bag')
  event.hide('projecte:orange_alchemical_bag')
  event.hide('projecte:magenta_alchemical_bag')
  event.hide('projecte:light_blue_alchemical_bag')
  event.hide('projecte:yellow_alchemical_bag')
  event.hide('projecte:lime_alchemical_bag')
  event.hide('projecte:pink_alchemical_bag')
  event.hide('projecte:gray_alchemical_bag')
  event.hide('projecte:light_gray_alchemical_bag')
  event.hide('projecte:cyan_alchemical_bag')
  event.hide('projecte:purple_alchemical_bag')
  event.hide('projecte:blue_alchemical_bag')
  event.hide('projecte:brown_alchemical_bag')
  event.hide('projecte:green_alchemical_bag')
  event.hide('projecte:red_alchemical_bag')
  event.hide('projecte:black_alchemical_bag')
  event.hide('projecte:dm_sword')
  event.hide('projecte:rm_sword')
  event.hide('projecte:rm_katar')
  event.hide('projecte:dm_helmet')
  event.hide('projecte:dm_chestplate')
  event.hide('projecte:dm_leggings')
  event.hide('projecte:dm_boots')
  event.hide('projecte:rm_helmet')
  event.hide('projecte:rm_chestplate')
  event.hide('projecte:rm_leggings')
  event.hide('projecte:rm_boots')
  event.hide('projecte:gem_helmet')
  event.hide('projecte:gem_chestplate')
  event.hide('projecte:gem_leggings')
  event.hide('projecte:gem_boots')
  event.hide('projecte:archangel_smite')
  event.hide('projecte:hyperkinetic_lens')
  event.hide('projecte:catalytic_lens')
  event.hide('projecte:klein_star_ein')
  event.hide('projecte:klein_star_zwei')
  event.hide('projecte:klein_star_drei')
  event.hide('projecte:klein_star_vier')
  event.hide('projecte:klein_star_sphere')
  event.hide('projecte:klein_star_omega')
  event.hide('projecte:repair_talisman')
  event.hide('projecte:harvest_goddess_band')
  event.hide('projecte:ignition_ring')
  event.hide('projecte:zero_ring')
  event.hide('projecte:swiftwolf_rending_gale')
  event.hide('projecte:watch_of_flowing_time')
  event.hide('projecte:gem_of_eternal_density')
  event.hide('projecte:mercurial_eye')
  event.hide('projecte:void_ring')
  event.hide('projecte:arcana_ring')
  event.hide('projecte:mind_stone')
  event.hide('projecte:divining_rod_1')
  event.hide('projecte:divining_rod_2')
  event.hide('projecte:divining_rod_3')
  event.hide('projecte:interdiction_torch')

  // Refined Storage

  event.hide('refinedstorage:white_controller')
  event.hide('refinedstorage:white_creative_controller')
  event.hide('refinedstorage:orange_controller')
  event.hide('refinedstorage:orange_creative_controller')
  event.hide('refinedstorage:magenta_controller')
  event.hide('refinedstorage:magenta_creative_controller')
  event.hide('refinedstorage:yellow_controller')
  event.hide('refinedstorage:yellow_creative_controller')
  event.hide('refinedstorage:lime_controller')
  event.hide('refinedstorage:lime_creative_controller')
  event.hide('refinedstorage:pink_controller')
  event.hide('refinedstorage:pink_creative_controller')
  event.hide('refinedstorage:gray_controller')
  event.hide('refinedstorage:gray_creative_controller')
  event.hide('refinedstorage:light_gray_controller')
  event.hide('refinedstorage:light_gray_creative_controller')
  event.hide('refinedstorage:cyan_controller')
  event.hide('refinedstorage:cyan_creative_controller')
  event.hide('refinedstorage:purple_controller')
  event.hide('refinedstorage:purple_creative_controller')
  event.hide('refinedstorage:blue_controller')
  event.hide('refinedstorage:blue_creative_controller')
  event.hide('refinedstorage:brown_controller')
  event.hide('refinedstorage:brown_creative_controller')
  event.hide('refinedstorage:green_controller')
  event.hide('refinedstorage:green_creative_controller')
  event.hide('refinedstorage:red_controller')
  event.hide('refinedstorage:red_creative_controller')
  event.hide('refinedstorage:black_controller')
  event.hide('refinedstorage:black_creative_controller')
  event.hide('refinedstorage:controller')
  event.hide('refinedstorage:wireless_grid')
  event.hide('refinedstorage:wireless_fluid_grid')
  event.hide('refinedstorage:wireless_crafting_monitor')
  event.hide('refinedstorageaddons:wireless_crafting_grid')
  event.hide('refinedstorage:portable_grid')


  // Ben's Sharks

  event.hide('benssharks:cellophane_noodles')
  event.hide('benssharks:jagged_helmet')
  event.hide('benssharks:jagged_chestplate')
  event.hide('benssharks:jagged_leggings')
  event.hide('benssharks:jagged_boots')
  event.hide('benssharks:krill_cake')
  event.hide('benssharks:krill_noodles')
  event.hide('benssharks:land_mine')
  event.hide('benssharks:sucker')
  event.hide('benssharks:shark_fin_soup')
  event.hide('benssharks:soup_sharkfin')
  event.hide('benssharks:starch')
  event.hide('benssharks:egg_capsule')
  event.hide('benssharks:dent')
  event.hide('benssharks:fish_bucket')
  event.hide('benssharks:maelstrom')
  event.hide('benssharks:maelstrom_bow')
  event.hide('benssharks:krill_item')
  event.hide('benssharks:raw_pilot_fish')
  event.hide('benssharks:cooked_pilot_fish')
  event.hide('benssharks:shark_fin')
  event.hide('benssharks:axoleather')
  event.hide('benssharks:axoscute')
  event.hide('benssharks:krill_bucket')
  event.hide('benssharks:shark_tooth')
  event.hide('benssharks:mutated_egg')

  // Avaritia

  event.hide('avaritia:neutron_ring')
  event.hide('avaritia:infinity_totem')
  event.hide('avaritia:infinity_ring')
  event.hide('avaritia:infinity_umbrella')
  event.hide('avaritia:infinity_hoe')
  event.hide('avaritia:infinity_shovel')
  event.hide('avaritia:infinity_axe')
  event.hide('avaritia:infinity_bucket')
  event.hide('avaritia:infinity_bow')
  event.hide('avaritia:infinity_crossbow')
  event.hide('avaritia:crystal_sword')
  event.hide('avaritia:crystal_hoe')
  event.hide('avaritia:crystal_pickaxe')
  event.hide('avaritia:crystal_shovel')
  event.hide('avaritia:crystal_axe')
  event.hide('avaritia:blaze_hoe')
  event.hide('avaritia:blaze_shovel')
  event.hide('avaritia:blaze_axe')
  event.hide('avaritia:neutron_horse_armor')
  event.hide('avaritia:blaze_cube')
  event.hide('avaritia:infinity_upgrade')
  event.hide('avaritia:diamond_lattice')
  event.hide('avaritia:crystal_matrix_ingot')
  event.hide('avaritia:neutron_pile')
  event.hide('avaritia:neutron_nugget')
  event.hide('avaritia:neutron_gear')
  event.hide('avaritia:infinity_nugget')
  event.hide('avaritia:infinity_catalyst')
  event.hide('avaritia:upgrade_smithing_template')
  event.hide('avaritia:singularity')
  event.hide('avaritia:eternal_singularity')
  event.hide('avaritia:record_fragment')
  event.hide('avaritia:star_fuel')
  event.hide('avaritia:refined_coal')
  event.hide('avaritia:endest_pearl')
  event.hide('avaritia:matter_cluster')
  event.hide('avaritia:enhancement_core')
  event.hide('avaritia:ultimate_stew')
  event.hide('avaritia:cosmic_meatballs')
  event.hide('avaritia:compressed_crafting_table')
  event.hide('avaritia:double_compressed_crafting_table')
  event.hide('avaritia:neutron')
  event.hide('avaritia:infinity')
  event.hide('avaritia:crystal_matrix')
  event.hide('avaritia:blaze_cube_block')
  event.hide('avaritia:compressed_chest')
  event.hide('avaritia:infinity_chest')
  event.hide('avaritia:infinity_clock')
  event.hide('avaritia:soul_farmland')
  event.hide('avaritia:diamond_lattice_block')
  event.hide('avaritia:star_fuel_block')
  event.hide('avaritia:refined_coal_block')
  event.hide('avaritia:sculk_crafting_table')
  event.hide('avaritia:nether_crafting_table')
  event.hide('avaritia:end_crafting_table')
  event.hide('avaritia:extreme_crafting_table')
  event.hide('avaritia:neutron_collector')
  event.hide('avaritia:dense_neutron_collector')
  event.hide('avaritia:denser_neutron_collector')
  event.hide('avaritia:densest_neutron_collector')
  event.hide('avaritia:neutron_compressor')
  event.hide('avaritia:extreme_smithing_table')
  event.hide('avaritia:extreme_anvil')
  event.hide('avaritia:endless_cake')

  // Mob Lassos

  event.hide('moblassos:golden_lasso')
  event.hide('moblassos:aqua_lasso')
  event.hide('moblassos:diamond_lasso')
  event.hide('moblassos:emerald_lasso')
  event.hide('moblassos:hostile_lasso')

  // Icarus

  event.hide('icarus:flandres_wings')
  event.hide('icarus:discords_wings')
  event.hide('icarus:zanzas_wings')

  // Mobile Beacons

  event.hide('mobilebeacon:mobile_beacon_iron_ii')
  event.hide('mobilebeacon:mobile_beacon_gold')
  event.hide('mobilebeacon:mobile_beacon_gold_ii')
  event.hide('mobilebeacon:mobile_beacon_emerald_ii')
  event.hide('mobilebeacon:mobile_beacon_diamond')
  event.hide('mobilebeacon:mobile_beacon_diamond_ii')

  // More Terraria Weapons

  event.hide('more_terraria_weapons:nights_edge')
  event.hide('more_terraria_weapons:excalibur')
  event.hide('more_terraria_weapons:coppe_shortsword')
  event.hide('more_terraria_weapons:bladeof_grass')
  event.hide('more_terraria_weapons:starfury')
  event.hide('more_terraria_weapons:muramasa')
  event.hide('more_terraria_weapons:volcano')
  event.hide('more_terraria_weapons:lights_bane')
  event.hide('more_terraria_weapons:blood_butcherer')
  event.hide('more_terraria_weapons:bee_keeper')
  event.hide('more_terraria_weapons:enchanted_sword')
  event.hide('more_terraria_weapons:broken_hero_sword')
  event.hide('more_terraria_weapons:crimtane_ingot')
  event.hide('more_terraria_weapons:crimtane_ore')
  event.hide('more_terraria_weapons:chlorophyte_ore')
  event.hide('more_terraria_weapons:chlorophyte_ingot')
  event.hide('more_terraria_weapons:demonite_ore')
  event.hide('more_terraria_weapons:demonite_ingot')
  event.hide('more_terraria_weapons:hallowed_ingot')
  event.hide('more_terraria_weapons:holy_water')
  event.hide('more_terraria_weapons:soulof_fright')
  event.hide('more_terraria_weapons:soulof_might')
  event.hide('more_terraria_weapons:soulof_sight')
  event.hide('more_terraria_weapons:sword_in_the_stone')
  event.hide('more_terraria_weapons:hellstone_ore')
  event.hide('more_terraria_weapons:hellstone')

  // Sophisticated Backpacks

  event.hide('sophisticatedbackpacks:copper_backpack')
  event.hide('sophisticatedbackpacks:filter_upgrade')
  // event.hide('sophisticatedbackpacks:advanced_filter_upgrade')
  event.hide('sophisticatedbackpacks:feeding_upgrade')
  // event.hide('sophisticatedbackpacks:advanced_feeding_upgrade')
  event.hide('sophisticatedbackpacks:pickup_upgrade')
  event.hide('sophisticatedbackpacks:advanced_pickup_upgrade')
  event.hide('sophisticatedbackpacks:magnet_upgrade')
  // event.hide('sophisticatedbackpacks:advanced_magnet_upgrade')
  event.hide('sophisticatedbackpacks:compacting_upgrade')
  event.hide('sophisticatedbackpacks:advanced_compacting_upgrade')
  event.hide('sophisticatedbackpacks:void_upgrade')
  // event.hide('sophisticatedbackpacks:advanced_void_upgrade')
  event.hide('sophisticatedbackpacks:restock_upgrade')
  event.hide('sophisticatedbackpacks:advanced_restock_upgrade')
  event.hide('sophisticatedbackpacks:deposit_upgrade')
  event.hide('sophisticatedbackpacks:advanced_deposit_upgrade')
  event.hide('sophisticatedbackpacks:refill_upgrade')
  event.hide('sophisticatedbackpacks:advanced_refill_upgrade')
  event.hide('sophisticatedbackpacks:inception_upgrade')
  // event.hide('sophisticatedbackpacks:everlasting_upgrade')
  event.hide('sophisticatedbackpacks:smelting_upgrade')
  event.hide('sophisticatedbackpacks:auto_smelting_upgrade')
  event.hide('sophisticatedbackpacks:smoking_upgrade')
  event.hide('sophisticatedbackpacks:auto_smoking_upgrade')
  event.hide('sophisticatedbackpacks:blasting_upgrade')
  event.hide('sophisticatedbackpacks:auto_blasting_upgrade')
  event.hide('sophisticatedbackpacks:stonecutter_upgrade')
  event.hide('sophisticatedbackpacks:stack_upgrade_starter_tier')
  // event.hide('sophisticatedbackpacks:stack_upgrade_tier_1')
  // event.hide('sophisticatedbackpacks:stack_upgrade_tier_2')
  // event.hide('sophisticatedbackpacks:stack_upgrade_tier_3')
  event.hide('sophisticatedbackpacks:stack_upgrade_tier_4')
  event.hide('sophisticatedbackpacks:stack_downgrade_tier_1')
  event.hide('sophisticatedbackpacks:stack_downgrade_tier_2')
  event.hide('sophisticatedbackpacks:stack_downgrade_tier_3')
  event.hide('sophisticatedbackpacks:stack_upgrade_omega_tier')
  event.hide('sophisticatedbackpacks:jukebox_upgrade')
  event.hide('sophisticatedbackpacks:advanced_jukebox_upgrade')
  event.hide('sophisticatedbackpacks:tool_swapper_upgrade')
  event.hide('sophisticatedbackpacks:advanced_tool_swapper_upgrade')
  event.hide('sophisticatedbackpacks:tank_upgrade')
  event.hide('sophisticatedbackpacks:battery_upgrade')
  event.hide('sophisticatedbackpacks:pump_upgrade')
  event.hide('sophisticatedbackpacks:advanced_pump_upgrade')
  event.hide('sophisticatedbackpacks:xp_pump_upgrade')
  event.hide('sophisticatedbackpacks:anvil_upgrade')
  event.hide('sophisticatedbackpacks:smithing_upgrade')
  event.hide('sophisticatedbackpacks:infinity_upgrade')
  event.hide('sophisticatedbackpacks:survival_infinity_upgrade')

  // Iron Bows

  event.hide('ironbows:iron_crossbow')
  event.hide('ironbows:golden_crossbow')
  event.hide('ironbows:diamond_crossbow')
  event.hide('ironbows:emerald_crossbow')
  event.hide('ironbows:netherite_crossbow')

})