#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 15 00:04:44 EDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.4-1.zip
enableShaders=false
