#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon May 05 22:35:16 EDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.4-1.zip
enableShaders=false
