#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 22 01:32:38 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.4-1.zip
enableShaders=false
